# Auto-generated by Cimas: Do not edit it manually!
# See https://github.com/metanorma/cimas
#!make
ifeq ($(OS),Windows_NT)
SHELL := pwsh -NoProfile
RM    := Remove-Item -Force
else
SHELL := /bin/bash
RM    := rm -f
endif

SRC := $(wildcard views/*.lutaml)
PNG := $(patsubst views/%.lutaml,images/%.png,$(SRC))

all: $(PNG)

images/%.png: views/%.lutaml
	lutaml-lml generate $< -o $@ -t png

clean:
	$(RM) images/*.png

.PHONY: all clean
