@startuml RelBib_Contributor
/'
Diagram:        RelBib_Citation
DateCreate:     30/08/2018
Description:    These bibliographic models are developed to consolidate and standardize the data models used for bibliographic and citation purposes.
                These models are meant to be fully compatible with ISO 690 and ISO TC 46’s (and SC 4, SC 9) work on bibliography.
                They are used extensively in the following projects as containers for bibliographic data management and for managing document metadata:

                - ISO Standards
                - CSD Standards
                - Chinese Standards (GB and family)
                - ISO bibliography gem

                Below are the UML diagrams.
                The document models are expressed as UML and as RelaxNG Compact (RNC) grammars; see discussion under Grammars. This repository contains the RNC grammars for the base BibliographicItem model, Citation model and the Contributor model.
                The document models are currently used by IsoDoc-based authoring tools for standards, which convert Asciidoctor source to XML representations of the document models, and validate the XML generated against the RNC schemas:

                - https://github.com/metanorma/metanorma-iso
                - https://github.com/metanorma/metanorma-csd
                - https://github.com/metanorma/metanorma-gb
                - And so on

                They are also used by tools that render those XML representations of the document models, into HTML and Microsoft Word:

                - https://github.com/metanorma/isodoc
                - https://github.com/metanorma/metanorma-csd (inheriting from isodoc)
                - https://github.com/metanorma/metanorma-gb (inheriting from isodoc)
                - And so on

History of changes:
> 12/01/2019: Add formattedAddress
    - 20190228: Person/uri, Organization/uri: allow multiple
    - 20190228: Populated ContactMethod, Address
    - 20190228: Annotate ContactMethod, Address, FullName
'/

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class Contributor {

}

together {
    class Person{
        +name: FullName[0..1]
        +affiliation: Affiliation[0..*]
        +identifier: PersonalIdentifier[0..*]
        +contact: ContactMethod[0..*]
        +uri: TypeUri[0..*]
    }

    class ContactMethod{
        +address: Address[0..1]
        +phone: String[0..1]
        +email: String[0..1]
        +uri: TypedUri[0..1]
    }

    class Organization{
        +name: LocalizedString
        +subdivision: LocalizedString[0..1]
        +abbreviation: LocalizedString[0..1]
        +uri: TypedUri[0..*]
        +identifier: OrgIdentifier[0..*]
        +contact: ContactMethod[0..*]
    }

class Address {
    +formattedAddress: String[0..1]
    +street: String[1..*]
    +city: String
    +state: String[0..1]
    +country: String
    +postcode: String[0..1]
}
}

together {
    class PersonIdentifier {
        +type: PersonalIdentifierType
        +value: String
    }

    class Affiliation{
        +name: LocalizedString[0..1]
        +description: FormattedString[0..*]
        +organization: Organization
    }

    class OrgIdentifier{
        +type: OrgIdentifierType
        +value: String
    }

}


together {
    enum PersonalIdentifierType <<enumeration>>{
        Isni
        Uri
    }

    class FullName{
        +prefix: LocalizedString[0..*]
        +forename: LocalizedString[0..*]
        +initial: LocalizedString[0..*]
        +surname: LocalizedString
        +addition: LocalizedString[0..*]
        +completeName: LocalizedString[0..1]
        +note: LocalizedString[0..1]
    }

    enum OrgIdentifierType <<enumeration>>{
        Orcid
        Uri
    }
}


'******* NOTES ********************************************************
note right of ContactMethod: the four options are mutually exclusive
note right of Address: may be revised in light of ISO 191606.\nformattedAddress is intended\nas an alternative to address broken down by field.
note right of FullName: completeName is mutually exclusive with the other name components


'******* CLASS RELATIONS **********************************************
Contributor <|-- Person
Contributor <|-- Organization

Person <-left- ContactMethod
ContactMethod -right-> Organization

Person <-- PersonIdentifier
PersonIdentifier <-- PersonalIdentifierType

Person <-left- Affiliation
Affiliation -right-> Organization

ContactMethod -[hidden]- Affiliation

Person <-- FullName

Organization <-- OrgIdentifier
OrgIdentifier <-- OrgIdentifierType

@enduml
